### ISSUE TITLE
Can't authenticate codeium on windows

### ISSUE THREAD

**Issue by sbstratos79** [Exafunction/codeium.nvim#73]
I have put the `uuidgen.exe` file in my path and can open the codeium authentication page. But when I input the generated token in neovim input box I get this error:
![image](https://github.com/jcdickinson/codeium.nvim/assets/4395586/cd581b52-c1ab-462d-b752-0b5da7dcb426)

This error is very similar to #44 but it occurs during authentication instead of during download. The culprit seems to be the `--compressed` flag.

I am on commit b1ff0d6c993e3d87a4362d2ccd6c660f7444599f because apparently `inputsecret` is not supported in neovim and prior to this commit, `input` was used.

**Comment by pqn** [comment]
Seems to me that the compressed flag shouldn't be included because of

https://github.com/Exafunction/codeium.nvim/commit/ed50d5eae1a8ab63dae3a0341f5f88794e8b4a0f

and:
https://github.com/nvim-lua/plenary.nvim/blob/9ce85b0f7dcfe5358c0be937ad23e456907d410b/lua/plenary/curl.lua#L207-L209

I will close this for now since ed50d5eae1a8ab63dae3a0341f5f88794e8b4a0f was supposed to address this, but feel free to comment if that's not the case.
